owner: buyproperly
repo: status
user-agent: BuyProperlyBot

sites:
  - name: BuyProperly AI
    url: https://www.buyproperly.ai
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    assignees:
      - krrajiv
  - name: BuyProperly Canada
    url: https://www.buyproperly.ai/ca
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    assignees:
      - krrajiv
  - name: BuyProperly USA
    url: https://www.buyproperly.ai/us
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    assignees:
      - krrajiv
  - name: BuyProperly App Canada
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    method: GET
    url: https://app.buyproperly.ca
    assignees:
      - krrajiv
  - name: BuyProperly App USA
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    method: GET
    url: https://app.buyproperly.com
    assignees:
      - krrajiv
  - name: BuyProperly Blog
    icon: https://cdn-img.buyproperly.com/company/favicon-48.png
    url: https://buyproperly.ai/blog/
    assignees:
      - krrajiv

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  cname: status.buyproperly.ai
  logoUrl: https://cdn-img.buyproperly.com/company/Logo-other.png
  name: Status
  introTitle: '**BuyProperly** lets you access high-yield alternative investment opportunities in real estate, private credit, private equity, hedge funds, and venture capital at BuyProperly. Start with just $2,500.'
  introMessage: This is BuyProperly status page which uses **real-time** data from our [GitHub repository](https://github.com/buyproperly/status).
  navbar:
    # - title: Properties
    #   href: https://buyproperly.ai/properties
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  favicon: https://cdn-img.buyproperly.com/company/favicon-48.png
  metaTags:
    - name: 'robots'
      content: 'noindex'
    - name: 'description'
      content: "Welcome to BuyProperly's home for real-time and historical data on system performance."
commitMessages:
  commitAuthorName: 'BuyProperly Bot'
  commitAuthorEmail: 'engineering@buyproperly.ca'
workflowSchedule:
  graphs: '0 0 * * *'
  responseTime: '0 23 * * *'
  staticSite: '0 1 * * *'
  summary: '0 0 * * *'
  updateTemplate: '0 0 * * *'
  updates: '0 3 * * *'
  uptime: '*/5 * * * *'
