owner: buyproperly
repo: status
user-agent: BuyProperlyBot

sites:
  - name: BuyProperly App
    url: https://www.buyproperly.ca
    icon: https://res.cloudinary.com/hv768g3im/image/upload/v1624260653/bp-assets/Logo_qfsqp1.png
    assignees:
      - ashwamegh
  - name: BuyProperly Server
    icon: https://res.cloudinary.com/hv768g3im/image/upload/v1624260653/bp-assets/Logo_qfsqp1.png
    method: POST
    url: $SERVER_SITE
    maxResponseTime: 5000
    assignees:
      - ashwamegh

status-website:
  cname: status.buyproperly.ca
  logoUrl: https://res.cloudinary.com/hv768g3im/image/upload/v1624260653/bp-assets/Logo_qfsqp1.png
  name: Status
  introTitle: "**BuyProperly** lets you invest in real estate to grow and diversify your wealth without traditional upfront costs."
  introMessage: This is BuyProperly status page which uses **real-time** data from our [GitHub repository](https://github.com/buyproperly/status).
  navbar:
    - title: Properties
      href: https://buyproperly.ca/properties
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  favicon: https://res.cloudinary.com/hv768g3im/image/upload/v1624262522/bp-assets/bp_logo_512-removebg-preview_lrpfnz.png
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "description"
      content: "Welcome to BuyProperly's home for real-time and historical data on system performance."